app = "weather-wanderer-wild-cherry-8496"
primary_region = "sjc"
console_command = "bin/rails console"

[build]

[deploy]
  release_command = "bin/rails db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = "https"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[processes]
  web = "bin/rails server -b 0.0.0.0"
